# Generated by Django 5.2.7 on 2025-11-02 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
