# Generated by Django 5.2.7 on 2025-11-02 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_card_next_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this deck', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='False when partnership is dissolved (soft delete)')),
                ('decks', models.ManyToManyField(blank=True, help_text='Decks shared between partners', related_name='partnerships', to='flashcards.deck')),
                ('user_a', models.ForeignKey(help_text='First partner in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(help_text='Second partner in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_a', 'is_active'], name='flashcards__user_a__37c776_idx'), models.Index(fields=['user_b', 'is_active'], name='flashcards__user_b__06ef77_idx')],
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='PartnershipInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique 6-character invitation code', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires after 7 days')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, help_text='User who accepted the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(help_text='User who created the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='flashcards__code_f4b382_idx'), models.Index(fields=['inviter', 'expires_at'], name='flashcards__inviter_6abc57_idx')],
            },
        ),
    ]
