# Generated by Django 5.2.7 on 2025-11-03 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_deck_created_by_partnership_partnershipinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_direction', models.CharField(choices=[('A_TO_B', 'Language A → Language B'), ('B_TO_A', 'Language B → Language A')], help_text='Which direction user is studying', max_length=10)),
                ('ease_factor', models.FloatField(default=2.5, help_text='Difficulty multiplier (1.3 minimum)')),
                ('interval', models.IntegerField(default=1, help_text='Days until next review')),
                ('repetitions', models.IntegerField(default=0, help_text='Consecutive successful reviews')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, help_text='When this card is due for review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User card progress records',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='context',
            field=models.TextField(blank=True, help_text='Usage example or additional notes'),
        ),
        migrations.AddField(
            model_name='card',
            name='language_a',
            field=models.TextField(blank=True, help_text='First language (e.g., Serbian word)', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='language_a_code',
            field=models.CharField(default='en', help_text="ISO 639-1 language code (e.g., 'sr', 'de', 'en')", max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='language_b',
            field=models.TextField(blank=True, help_text='Second language (e.g., German translation)', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='language_b_code',
            field=models.CharField(default='en', help_text='ISO 639-1 language code', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='study_direction',
            field=models.CharField(blank=True, choices=[('A_TO_B', 'Language A → Language B'), ('B_TO_A', 'Language B → Language A')], help_text='Direction studied for this review', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='study_direction',
            field=models.CharField(blank=True, choices=[('A_TO_B', 'Language A → Language B'), ('B_TO_A', 'Language B → Language A')], help_text='Primary direction for this session (null if mixed)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ease_factor',
            field=models.FloatField(blank=True, default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'created_at'], name='flashcards__deck_id_24b186_idx'),
        ),
        migrations.AddField(
            model_name='usercardprogress',
            name='card',
            field=models.ForeignKey(help_text='The card being studied', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='flashcards.card'),
        ),
        migrations.AddField(
            model_name='usercardprogress',
            name='user',
            field=models.ForeignKey(help_text='User studying this card', on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercardprogress',
            index=models.Index(fields=['user', 'next_review'], name='flashcards__user_id_8db61d_idx'),
        ),
        migrations.AddIndex(
            model_name='usercardprogress',
            index=models.Index(fields=['user', 'card'], name='flashcards__user_id_f8193b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercardprogress',
            unique_together={('user', 'card', 'study_direction')},
        ),
    ]
