# Generated by Django 5.2.7 on 2025-11-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_usercardprogress_card_context_card_language_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='language_a_code',
        ),
        migrations.RemoveField(
            model_name='card',
            name='language_b_code',
        ),
    ]
