# Generated by Django 5.2.7 on 2025-11-08 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this deck (historical record)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(help_text='Primary owner of the deck (for filtering and cascade deletion)', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
