# Generated by Django 5.2.15 on 2026-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='share_pending',
            field=models.BooleanField(default=False, help_text='Owner intends to share this deck, but has no active partnership yet. Promoted to a real shared deck when a partnership is formed.'),
        ),
    ]
